name: "Build on Windows x86_64"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "PHP version to build"
        required: true
        type: choice
        default: "8.4"
        options:
          - "8.4"
          - "8.3"
          - "8.2"
          - "8.1"

      extensions:
        description: "Extensions to build (comma separated)"
        required: true
        type: string
        default: "bcmath,bz2,calendar,ctype,curl,dom,ev,exif,ffi,fileinfo,filter,iconv,libxml,mbregex,mbstring,opcache,openssl,pdo,pdo_sqlite,phar,session,shmop,simplexml,soap,sockets,sodium,sqlite3,tokenizer,xml,xmlreader,xmlwriter,zip,zlib,gd"

      libs:
        description: "Libraries to build (comma separated)"
        type: string
        default: "freetype,libjpeg,libavif,libwebp"

      build-cli:
        description: "Build CLI binary"
        type: boolean
        default: true

      build-micro:
        description: "Build PHPMicro binary"
        type: boolean
        default: false

      prefer-pre-built:
        description: "Prefer pre-built binaries"
        type: boolean
        default: true

      debug:
        description: "Show full build logs"
        type: boolean
        default: false

      no-strip:
        description: "Keep debug symbols for debugging"
        type: boolean
        default: false

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: "Build ${{ inputs.version }} on Windows x86_64"
    runs-on: windows-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Cache SPC binary"
        id: cache-spc-binary
        uses: actions/cache@v4
        with:
          path: spc.exe
          key: spc-binary

      - name: "Download SPC binary"
        if: steps.cache-spc-binary.outputs.cache-hit != 'true'
        run: curl.exe -fsSL -o spc.exe https://dl.static-php.dev/static-php-cli/spc-bin/nightly/spc-windows-x64.exe

      - name: "Run SPC"
        shell: bash
        run: ./spc --version
