name: "Release Build"

on:
  release:
    types: [ created ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Trigger builds for all platforms"
        run: |
          gh workflow run build-on-windows-2022-x64.yml
